import { Mongo } from 'meteor/mongo';
import { TaskType } from '../types/Task';
import SimpleSchema from 'simpl-schema';

export const TasksCollection = new Mongo.Collection<TaskType>('tasks');

TasksCollection.schema = new SimpleSchema({
    _id: {
        type: String,
        optional: true,  // `_id` is optional because it will be generated by MongoDB
    },
    text: {
        type: String,
    },
    isChecked: {
        type: Boolean, 
        defaultValue: false,
    },
});

